"""Initial migration

Revision ID: 207bc87ea655
Revises: 
Create Date: 2025-10-09 12:00:43.166258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207bc87ea655'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('walacor_tx_id', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_created_at', 'artifacts', ['created_at'], unique=False)
    op.create_index('idx_artifact_loan_type', 'artifacts', ['loan_id', 'artifact_type'], unique=False)
    op.create_index('idx_artifact_walacor_tx', 'artifacts', ['walacor_tx_id'], unique=False)
    op.create_index(op.f('ix_artifacts_loan_id'), 'artifacts', ['loan_id'], unique=False)
    op.create_index(op.f('ix_artifacts_payload_sha256'), 'artifacts', ['payload_sha256'], unique=False)
    op.create_table('artifact_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('walacor_tx_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_artifact_type', 'artifact_events', ['artifact_id', 'event_type'], unique=False)
    op.create_index('idx_event_created_at', 'artifact_events', ['created_at'], unique=False)
    op.create_index('idx_event_created_by', 'artifact_events', ['created_by'], unique=False)
    op.create_index('idx_event_type', 'artifact_events', ['event_type'], unique=False)
    op.create_index('idx_event_walacor_tx', 'artifact_events', ['walacor_tx_id'], unique=False)
    op.create_index(op.f('ix_artifact_events_artifact_id'), 'artifact_events', ['artifact_id'], unique=False)
    op.create_table('artifact_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_content_type', 'artifact_files', ['content_type'], unique=False)
    op.create_index('idx_file_sha256', 'artifact_files', ['sha256'], unique=False)
    op.create_index('idx_file_size', 'artifact_files', ['size_bytes'], unique=False)
    op.create_index(op.f('ix_artifact_files_artifact_id'), 'artifact_files', ['artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_files_artifact_id'), table_name='artifact_files')
    op.drop_index('idx_file_size', table_name='artifact_files')
    op.drop_index('idx_file_sha256', table_name='artifact_files')
    op.drop_index('idx_file_content_type', table_name='artifact_files')
    op.drop_table('artifact_files')
    op.drop_index(op.f('ix_artifact_events_artifact_id'), table_name='artifact_events')
    op.drop_index('idx_event_walacor_tx', table_name='artifact_events')
    op.drop_index('idx_event_type', table_name='artifact_events')
    op.drop_index('idx_event_created_by', table_name='artifact_events')
    op.drop_index('idx_event_created_at', table_name='artifact_events')
    op.drop_index('idx_event_artifact_type', table_name='artifact_events')
    op.drop_table('artifact_events')
    op.drop_index(op.f('ix_artifacts_payload_sha256'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_loan_id'), table_name='artifacts')
    op.drop_index('idx_artifact_walacor_tx', table_name='artifacts')
    op.drop_index('idx_artifact_loan_type', table_name='artifacts')
    op.drop_index('idx_artifact_created_at', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
