"""attestations + provenance

Revision ID: e024131443c3
Revises: 22edcc43e642
Create Date: 2025-10-09 16:31:12.821541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e024131443c3'
down_revision: Union[str, Sequence[str], None] = '22edcc43e642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('etid', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('issued_by', sa.String(length=120), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attestation_artifact_kind', 'attestations', ['artifact_id', 'kind'], unique=False)
    op.create_index(op.f('ix_attestations_artifact_id'), 'attestations', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_attestations_etid'), 'attestations', ['etid'], unique=False)
    op.create_table('provenance_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('child_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_artifact_id', 'child_artifact_id', name='uq_prov_parent_child')
    )
    op.create_index(op.f('ix_provenance_links_child_artifact_id'), 'provenance_links', ['child_artifact_id'], unique=False)
    op.create_index(op.f('ix_provenance_links_parent_artifact_id'), 'provenance_links', ['parent_artifact_id'], unique=False)
    # Note: etid column was already made non-nullable in previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: etid column alteration removed due to SQLite limitations
    op.drop_index(op.f('ix_provenance_links_parent_artifact_id'), table_name='provenance_links')
    op.drop_index(op.f('ix_provenance_links_child_artifact_id'), table_name='provenance_links')
    op.drop_table('provenance_links')
    op.drop_index(op.f('ix_attestations_etid'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_artifact_id'), table_name='attestations')
    op.drop_index('ix_attestation_artifact_kind', table_name='attestations')
    op.drop_table('attestations')
    # ### end Alembic commands ###
